workflows:
  unity-ios-workflow:
    name: Module workflow
    max_build_duration: 120
    environment:
      xcode: 15.0.1

    scripts:
      - name: Delete derived data
        script: rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Install pods
        script: pod install
      - name: build
        script: ./build.sh
    artifacts:
      - build/build/*
